security:
    providers:
        db_provider:
            entity:
                class: App\Domain\Entity\User
                property: username

    encoders:
        App\Domain\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/user, roles: [user] }
        - { path: ^/redactor, roles: [redactor] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: /auth/login
                check_path: /auth/login
                default_target_path: login_check

            logout:
                path:   /auth/logout
                target: /auth/login

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
